sudo: false
language: java
jdk:
- oraclejdk8
cache:
  directories:
    - $HOME/.gradle/caches/*
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
addons:
  apt:
    packages:
    - texlive-fonts-recommended
    - texlive-latex-extra
    - texlive-fonts-extra
    - dvipng
    - texlive-latex-recommended
after_success:
    - bash <(curl -s https://codecov.io/bash)
install:
    - ./gradlew build --stacktrace --info
    - ls -R $HOME/.recipes2pdf
